### ISSUE TITLE
Edit file's json data

### ISSUE THREAD

**Issue by maxfadeev** [yegor86/my-cloud-drive#26]
"created":1448286443627,"updated":1448286443627 - to send formatted data like 19/5/2012 9:01 PM
"extension":"txt" - change to 'type' and send values like 'image', 'dir', etc
fileName, filePath - could be simply name, path
"folder":true - "isFolder":true

**Comment by yegor86** [comment]
@masdeft,
Regarding _create_ and _updated_ dates, I think that it's better to convert the timestamp to string on the client site. 
It should be done on the client site because the backend does not take into account client's timezone

**Comment by maxfadeev** [comment]
Yes, you right. Moreover using Angular it is easy to convert dates

**Comment by Sigora** [comment]
closing

**Comment by Sigora** [comment]
resolved
