### ISSUE TITLE
Download file feature corrupts original file 

### ISSUE THREAD

**Issue by yegor86** [yegor86/my-cloud-drive#46]
Try to upload and then download image file via curl

``` bash
curl -i -O http://localhost:3030/files/download/admin@mail.com/dir1/ACP-8927.png
```

Compare the downloaded file with original one

Attaching example
![test](https://cloud.githubusercontent.com/assets/487676/12652788/364e2748-c5f5-11e5-8011-89370dab5265.png)

**Comment by Sigora** [comment]
Works fine for me
